version: '3.1'

services: 
  postgres:
    image: postgres:12.1-alpine
    container_name: pgsql
    environment: 
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./initdb/:/docker-entrypoint-initdb.d/  
    ports:
     - 5432:5432  
  pgadmin:
    image: dpage/pgadmin4:4.15
    container_name: pgadmin
    environment: 
    - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
    - PGADMIN_DEFAULT_PASSWORD=admin
    volumes: 
    - ./localconnection.json:/pgadmin4/servers.json
    ports:
    - 8080:80

